name: Release Drafter

on:
  push:
    branches:
      - main

permissions:
  contents: read

jobs:
  update_release_draft:
    permissions:
      contents: write
      pull-requests: write
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Prepare checkout token
        id: generate_token
        uses: tibdex/github-app-token@b62528385c34dbc9f38e5f4225ac829252d1ea92
        with:
          app_id: ${{ secrets.TEMPORAL_CICD_APP_ID }}
          private_key: ${{ secrets.TEMPORAL_CICD_PRIVATE_KEY }}

      - uses: release-drafter/release-drafter@v6
        env:
          GITHUB_TOKEN: ${{ steps.generate_token.outputs.token }}
